#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."



export DEFER_PYDANTIC_BUILD=false

echo "==> Running tests"
uv run pytest "$@"

echo "==> Running tests with Pydantic v1"
uv run --isolated --all-extras --group=pydantic-v1 pytest "$@"
